### ISSUE TITLE
Broken specs

### ISSUE THREAD

**Issue by jcf** [arachne-framework/arachne-core#43]
To start an Arachne application with instrumentation enabled requires the following spec changes:

``` clj
;; Before
(s/fdef arachne.core.config/update
  :args (s/cat :config ::config, :txdata ::txdata)
  :ret ::config)

;; After with provenance added
(s/fdef arachne.core.config/update
  :args (s/cat :config ::config
               :txdata ::txdata
               :add-provenance-txdata? (s/? boolean?))
  :ret ::config)

;; Before
(s/fdef arachne.core.config/q
  :args (s/cat :config ::config,
               :find-expr ::find-expr,
               :sources (s/or :not-present nil?
                              :varargs coll?)))

;; After with a more lax `:sources` spec
(s/fdef arachne.core.config/q
  :args (s/cat :config ::config,
               :find-expr ::find-expr,
               :sources (s/? any?)))
```

I've added the provenance txdata boolean to `update`, and changed `:sources` on `q` to allow any varargs (the `any?` could be a spec for whatever the other sources are).

I can open a PR with the above spec changes if you like.

Thanks for your work on Arachne, @levand!

**Comment by jcf** [comment]
My change to the `q` spec isn't right apparently. Relevant stacktrace:

```
clojure.lang.ExceptionInfo: Call to #'arachne.core.config/q did not conform to spec:
In: [3] val: (:site.server/hello) fails at: [:args] predicate: (cat :config :arachne.core.config.specs/config :find-expr :arachne.core.config.specs/find-expr :sources (? any?)),  Extra input
 {:clojure.spec.alpha/problems [{:path [:args], :reason "Extra input", :pred (clojure.spec.alpha/cat :config :arachne.core.config.specs/config :find-expr :arachne.core.config.specs/find-expr :sources (clojure.spec.alpha/? clojure.core/any?)), :val (:site.server/hello), :via [], :in [3]}], :clojure.spec.alpha/spec #object[clojure.spec.alpha$regex_spec_impl$reify__2436 0x6c69578a "clojure.spec.alpha$regex_spec_impl$reify__2436@6c69578a"], :clojure.spec.alpha/value (#DatomicConfig[-1159558851] [:find ?e . :in $ ?a ?v :where [?e ?a ?v]] :arachne/id :site.server/hello), :clojure.spec.alpha/args (#DatomicConfig[-1159558851] [:find ?e . :in $ ?a ?v :where [?e ?a ?v]] :arachne/id :site.server/hello), :clojure.spec.alpha/failure :instrument, :clojure.spec.test.alpha/caller {:file "reified_ref.clj", :line 90, :var-scope arachne.core.config.reified-ref/resolve-rref}}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at clojure.spec.test.alpha$spec_checking_fn$conform_BANG___2938.invoke(alpha.clj:131)
	at clojure.spec.test.alpha$spec_checking_fn$fn__2943.doInvoke(alpha.clj:139)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at arachne.core.config.reified_ref$resolve_rref.invokeStatic(reified_ref.clj:90)
	at arachne.core.config.reified_ref$resolve_rref.invoke(reified_ref.clj:87)
	at arachne.core.config.reified_ref$resolve_reified_references$fn__17907.invoke(reified_ref.clj:143)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$reduce.invoke(core.clj:6730)
	at arachne.core.config.reified_ref$resolve_reified_references.invokeStatic(reified_ref.clj:144)
	at arachne.core.config.reified_ref$resolve_reified_references.invoke(reified_ref.clj:135)
	at arachne.core.module$config_STAR_.invokeStatic(module.clj:205)
	at arachne.core.module$config_STAR_.invoke(module.clj:195)
	at arachne.core.module$config.invokeStatic(module.clj:241)
	at arachne.core.module$config.invoke(module.clj:228)
	at arachne.core$config.invokeStatic(core.clj:138)
	at arachne.core$config.doInvoke(core.clj:135)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.spec.test.alpha$spec_checking_fn$fn__2943.doInvoke(alpha.clj:141)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at site.repl$dev_system.invokeStatic(repl.clj:21)
	at site.repl$dev_system.invoke(repl.clj:18)
	at site.repl$eval48117$fn__48118.invoke(repl.clj:23)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:305)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5450)
	at clojure.core$alter_var_root.doInvoke(core.clj:5445)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at com.stuartsierra.component.repl$start.invokeStatic(repl.clj:37)
	at com.stuartsierra.component.repl$start.invoke(repl.clj:34)
	at clojure.lang.Var.invoke(Var.java:377)
	at clojure.tools.namespace.repl$do_refresh.invokeStatic(repl.clj:100)
	at clojure.tools.namespace.repl$do_refresh.invoke(repl.clj:83)
	at clojure.tools.namespace.repl$refresh.invokeStatic(repl.clj:145)
	at clojure.tools.namespace.repl$refresh.doInvoke(repl.clj:128)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at com.stuartsierra.component.repl$reset.invokeStatic(repl.clj:60)
	at com.stuartsierra.component.repl$reset.invoke(repl.clj:55)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at com.stuartsierra.component.user_helpers$invoke.invokeStatic(user_helpers.clj:32)
	at com.stuartsierra.component.user_helpers$invoke.doInvoke(user_helpers.clj:26)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at com.stuartsierra.component.user_helpers$go.invokeStatic(user_helpers.clj:46)
	at com.stuartsierra.component.user_helpers$go.invoke(user_helpers.clj:42)
	at com.stuartsierra.component.user_helpers$reset.invokeStatic(user_helpers.clj:53)
	at com.stuartsierra.component.user_helpers$reset.invoke(user_helpers.clj:49)
	at user$eval15068.invokeStatic(form-init5558734642710885670.clj:75)
	at user$eval15068.invoke(form-init5558734642710885670.clj:75)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7025)
	at clojure.core$eval.invokeStatic(core.clj:3206)
	at clojure.core$eval.invoke(core.clj:3202)
	at clojure.main$repl$read_eval_print__8572$fn__8575.invoke(main.clj:243)
	at clojure.main$repl$read_eval_print__8572.invoke(main.clj:243)
	at clojure.main$repl$fn__8581.invoke(main.clj:261)
	at clojure.main$repl.invokeStatic(main.clj:261)
	at clojure.main$repl.doInvoke(main.clj:177)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at refactor_nrepl.ns.slam.hound.regrow$wrap_clojure_repl$fn__14622.doInvoke(regrow.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__3761.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__3806$fn__3809.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__3801.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
